### ISSUE TITLE
RNSVGRect crash issue on iOS 14

### ISSUE THREAD

**Issue by awpogodin** [react-native-svg/react-native-svg#1475]
Hi,
our React Native app uses the **react-native-svg** library and some of our users with **iOS 14** are constantly catching crashes, but we can't catch them, so we don't have a TC. Maybe you fixed this in the new versions or have any ideas where we need to look? Thanks in advance.

**Our current versions are**
_react-native: 0.62.2
react-native-svg: 10.1.0_

Here is the stack trace that we catch in **Firebase Crashlytics**. Kindly help with investigation.

```
Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x1b0a5c95c __pthread_kill + 8
1  libsystem_pthread.dylib        0x1cb9af9e8 pthread_kill + 212
2  libsystem_c.dylib              0x18eda7934 abort + 100
3  libsystem_c.dylib              0x18eda6d34 err + 286
4  CoreGraphics                   0x187b8b654 CGPathAddUnevenCornersRoundedRect + 486
5  mobileClient                   0x1004121a4 -[RNSVGRect getPath:]
 + 103 (RNSVGRect.m:103)
6  mobileClient                   0x10040258c __22-[RNSVGGroup getPath:]_block_invoke + 158 (RNSVGGroup.m:158)
7  mobileClient                   0x100409790 -[RNSVGNode traverseSubviews:]
 + 584 (RNSVGNode.m:584)
8  mobileClient                   0x10040243c -[RNSVGGroup getPath:]
 + 165 (RNSVGGroup.m:165)
9  mobileClient                   0x100408a60 -[RNSVGNode getClipPath:]
 + 328 (RNSVGNode.m:328)
10 mobileClient                   0x100408b80 -[RNSVGNode clip:]
 + 357 (RNSVGNode.m:357)
11 mobileClient                   0x100413e4c -[RNSVGRenderable renderLayerTo:rect:]
 + 404 (RNSVGRenderable.m:404)
12 mobileClient                   0x1004132cc -[RNSVGRenderable renderTo:rect:]
 + 283 (RNSVGRenderable.m:283)
13 mobileClient                   0x100402024 __33-[RNSVGGroup renderGroupTo:rect:]_block_invoke + 59 (RNSVGGroup.m:59)
14 mobileClient                   0x100409790 -[RNSVGNode traverseSubviews:]
 + 584 (RNSVGNode.m:584)
15 mobileClient                   0x1004019a8 -[RNSVGGroup renderGroupTo:rect:]
 + 82 (RNSVGGroup.m:82)
16 mobileClient                   0x1004132cc -[RNSVGRenderable renderTo:rect:]
 + 283 (RNSVGRenderable.m:283)
17 mobileClient                   0x100402024 __33-[RNSVGGroup renderGroupTo:rect:]_block_invoke + 59 (RNSVGGroup.m:59)
18 mobileClient                   0x100409790 -[RNSVGNode traverseSubviews:]
 + 584 (RNSVGNode.m:584)
19 mobileClient                   0x1004019a8 -[RNSVGGroup renderGroupTo:rect:]
 + 82 (RNSVGGroup.m:82)
20 mobileClient                   0x1004132cc -[RNSVGRenderable renderTo:rect:]
 + 283 (RNSVGRenderable.m:283)
21 mobileClient                   0x100417f1c -[RNSVGSvgView drawToContext:withRect:]
 + 196 (RNSVGSvgView.m:196)
22 mobileClient                   0x100418218 -[RNSVGSvgView drawRect:]
 + 228 (RNSVGSvgView.m:228)
23 UIKitCore                      0x188ea0b48 -[UIView(CALayerDelegate) drawLayer:inContext:]
 + 584
24 QuartzCore                     0x1893a0c58 -[CALayer drawInContext:]
 + 308
25 QuartzCore                     0x189273d28 CABackingStoreUpdate_ + 176
26 QuartzCore                     0x1893aa0c0 invocation function for block in CA::Layer::display_() + 52
27 QuartzCore                     0x1893a03d8 -[CALayer _display] + 1680
28 QuartzCore                     0x1893b32e4 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 416
29 QuartzCore                     0x1892ff500 CA::Context::commit_transaction(CA::Transaction, double, double) + 416
30 QuartzCore                     0x189329698 CA::Transaction::commit() + 728
31 QuartzCore                     0x18932a948 CA::Transaction::observer_callback(__CFRunLoopObserver, unsigned long, void) + 92
32 CoreFoundation                 0x1860dbecc _CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION_ + 32
33 CoreFoundation                 0x1860d65b0 __CFRunLoopDoObservers + 604
34 CoreFoundation                 0x1860d6af8 __CFRunLoopRun + 960
35 CoreFoundation                 0x1860d6200 CFRunLoopRunSpecific + 572
36 GraphicsServices               0x19c1d1598 GSEventRunModal + 160
37 UIKitCore                      0x18899c004 -[UIApplication _run] + 1052
38 UIKitCore                      0x1889a15d8 UIApplicationMain + 164
39 mobileClient                   0x10032fb80 main + 14 (main.m:14)
40 libdyld.dylib                  0x185db5598 start + 4
```

**Comment by awpogodin** [comment]
We fixed it. The app crashed when negative width and height were passed to the Rect component.

**Comment by uripre** [comment]
@awpogodin I can see you reopened the ticket. Did you manage to fix it or is it still an issue?

**Comment by csokdara-thefoundry-app** [comment]
I got this crash on production app also here's crashlytics.

I have tried to find any negative value and push an update but the crash is still present and I do not know what cause this crash.

Our current versions are
react-native: 0.63.4
react-native-svg: 12.1.0
react-native-chart-kit: 6.6.1 (the crash screen use this library to display bar chart)

> Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x1add4984c __pthread_kill + 8
1  libsystem_pthread.dylib        0x1ca6309e8 pthread_kill + 212
2  libsystem_c.dylib              0x18ab058f4 abort + 100
3  libsystem_c.dylib              0x18ab04cf4 err + 286
4  CoreGraphics                   0x183853720 CGPathAddUnevenCornersRoundedRect + 486
5  KOTRAriel                      0x1047fe890 -[RNSVGRect getPath:] + 103 (RNSVGRect.m:103)
6  KOTRAriel                      0x1048000d0 -[RNSVGRenderable renderLayerTo:rect:] + 355 (RNSVGRenderable.m:355)
7  KOTRAriel                      0x1047ffa1c -[RNSVGRenderable renderTo:rect:] + 284 (RNSVGRenderable.m:284)
8  KOTRAriel                      0x1047edaa0 __33-[RNSVGGroup renderGroupTo:rect:]_block_invoke + 59 (RNSVGGroup.m:59)
9  KOTRAriel                      0x1047f5420 -[RNSVGNode traverseSubviews:] + 593 (RNSVGNode.m:593)
10 KOTRAriel                      0x1047ed46c -[RNSVGGroup renderGroupTo:rect:] + 80 (RNSVGGroup.m:80)
11 KOTRAriel                      0x1047ffa1c -[RNSVGRenderable renderTo:rect:] + 284 (RNSVGRenderable.m:284)
12 KOTRAriel                      0x1047edaa0 __33-[RNSVGGroup renderGroupTo:rect:]_block_invoke + 59 (RNSVGGroup.m:59)
13 KOTRAriel                      0x1047f5420 -[RNSVGNode traverseSubviews:] + 593 (RNSVGNode.m:593)
14 KOTRAriel                      0x1047ed46c -[RNSVGGroup renderGroupTo:rect:] + 80 (RNSVGGroup.m:80)
15 KOTRAriel                      0x1047ffa1c -[RNSVGRenderable renderTo:rect:] + 284 (RNSVGRenderable.m:284)
16 KOTRAriel                      0x104804798 -[RNSVGSvgView drawToContext:withRect:] + 196 (RNSVGSvgView.m:196)
17 KOTRAriel                      0x104804aa4 -[RNSVGSvgView drawRect:] + 228 (RNSVGSvgView.m:228)
18 UIKitCore                      0x184b7e588 -[UIView(CALayerDelegate) drawLayer:inContext:] + 584
19 QuartzCore                     0x185084064 -[CALayer drawInContext:] + 308
20 QuartzCore                     0x184f555a8 CABackingStoreUpdate_ + 176
21 QuartzCore                     0x18508d5a4 invocation function for block in CA::Layer::display_() + 52
22 QuartzCore                     0x1850837e4 -[CALayer _display] + 1680
23 QuartzCore                     0x1850967fc CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 416
24 QuartzCore                     0x184fe1d7c CA::Context::commit_transaction(CA::Transaction*, double, double*) + 416
25 QuartzCore                     0x18500bf40 CA::Transaction::commit() + 728
26 QuartzCore                     0x18500d1f0 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 92
27 CoreFoundation                 0x181d8987c __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
28 CoreFoundation                 0x181d83f50 __CFRunLoopDoObservers + 604
29 CoreFoundation                 0x181d84498 __CFRunLoopRun + 960
30 CoreFoundation                 0x181d83ba0 CFRunLoopRunSpecific + 572
31 GraphicsServices               0x198aec598 GSEventRunModal + 160
32 UIKitCore                      0x1846752f4 -[UIApplication _run] + 1052
33 UIKitCore                      0x18467a874 UIApplicationMain + 164
34 KOTRAriel                      0x10443ee00 main + 7 (main.m:7)
35 libdyld.dylib                  0x181a62568 start + 4

**Comment by MaximeCrp** [comment]
> We fixed it. The app crashed when negative width and height were passed to the Rect component.

Thank you for this info. For us it was not exactly the issue but thanks to this comment we found within a minute. It was crashing on iOS when values were 0 or -0

**Comment by thecodecafe** [comment]
So the problem may be that one of the values you're using for the size may be zero or a negative value, try to ensure the values are always 1 or more before using them to set the width or height of your content loader.
That fixed the issue for my but I'll keep monitoring, I'm in heavy developement right now so if I don't report back with an issue 24 hours then that means all is well.
